# Stage 1: Base image for development
FROM node:18-alpine AS development

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY ../package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY .. .

# Expose the development server port
EXPOSE 6004

# Command to run the application in development mode
CMD ["npm", "run", "dev"]
