services:
  development:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    image: splitwise-frontend-dev
    ports:
      - "6002:6002"
    volumes:
      - ../:/app
      - /app/node_modules/

  production:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    image: splitwise-frontend-prod
    ports:
      - "6002:6002"
    restart: always
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_BASE_URL=http://localhost:4002/api/v1