services:
  development:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    image: splitwise-frontend-dev
    ports:
      - "6002:6002"
    volumes:
      - ../:/app
      - /app/node_modules/

  production:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    image: splitwise-frontend-prod
    ports:
      - "6002:6002"
    restart: always