services:
  development:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    image: splitwise-dev
    ports:
      - "4004:4004"
    volumes:
      - ./:/app
      - /app/node_modules/
    environment:
      - NODE_ENV=development
      - PORT=4004

  production:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    image: splitwise-prod
    ports:
      - "7002:7002"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=7002
